// Header

enum E_VEHICLE_DATA
{
    E_VEHICLE_DATA_ID,
    E_VEHICLE_DATA_MODEL,
    E_VEHICLE_DATA_OWNER,
    
    Float:E_VEHICLE_DATA_POS,
    Float:E_VEHICLE_DATA_HEALTH,

    E_VEHICLE_DATA_COLOR_1,
    E_VEHICLE_DATA_COLOR_2,
};

new
    gVehicleInfo[MAX_VEHICLES][E_VEHICLE_DATA];