// Settings

#define MAX_HOUSE_ADDRESS 35
#define MAX_HOUSE_DESCRIPTION 128

#define PICKUP_SALE 19524
#define PICKUP_OWNED 1273

// Header

enum E_HOUSE_DATA
{
    E_HOUSE_DATA_ID,
    E_HOUSE_DATA_ADDRESS[MAX_HOUSE_ADDRESS],
    E_HOUSE_DATA_DESCRIPTION[MAX_HOUSE_DESCRIPTION],
    E_HOUSE_DATA_OWNER,

    bool:E_HOUSE_DATA_OWNED,
    bool:E_HOUSE_DATA_LOCKED,

    E_HOUSE_DATA_ICON,
    E_HOUSE_DATA_PICKUP,
    E_HOUSE_DATA_PRICE,

    E_HOUSE_DATA_EXTERIOR,
    E_HOUSE_DATA_INTERIOR,

    Float:E_HOUSE_DATA_EXTERIOR_X,
    Float:E_HOUSE_DATA_EXTERIOR_Y,
    Float:E_HOUSE_DATA_EXTERIOR_Z,
    
    Float:E_HOUSE_DATA_INTERIOR_X,
    Float:E_HOUSE_DATA_INTERIOR_Y,
    Float:E_HOUSE_DATA_INTERIOR_Z,

    Text3D:E_HOUSE_DATA_LABEL
}

new 
    gHouseInfo[MAX_HOUSES][E_HOUSE_DATA];